### ISSUE TITLE
[SPRINT] Auto-update the publication count in the DESC landing page

### ISSUE THREAD

**Issue by arunkannawadi** [LSSTDESC/SprintWeek2021#10]
# Auto-update the publication count in the DESC landing page

The sprint will use the existing publication bot to update the `index.html` landing page to automatically increment the paper count.

Contacts: @arunkannawadi 
Day/Time: Asynchronous
Main communication channel: #desc-website
GitHub repo: https://github.com/LSSTDESC/lsstdesc.github.io

## Goals and deliverable

- [x]  Update the publication bot script to modify the paper count in the landing page

## Resources and skills needed
Minimal Python familiarity and almost no HTML knowledge.

**Comment by yymao** [comment]
Happy to help!

**Comment by kadrlica** [comment]
Do we want to expand this hack to connect the DESC PubDB to the publication page on the DESC website?

**Comment by yymao** [comment]
Does DESC PubDB has a public accessible URL that lists the publication information in some machine readable format?

**Comment by kadrlica** [comment]
So "yes" to the machine readable format. We'd need to figure out where we want to put it. My understanding is that SLACs publicly accessible html pages for users are not what they used to be.

**Comment by kadrlica** [comment]
@yymao are you interested in giving this a shot this week?

**Comment by yymao** [comment]
I am, but I am stretched a bit thin this week because I have to attend another virtual conference. 

Does the URL already exist (if so, can you DM me), and what we need to do is to interface it with the website, or does what we need to do this week is to create that URL?

**Comment by arunkannawadi** [comment]
^ PR with the original target above.

**Comment by kadrlica** [comment]
Sorry, @yymao what we would need to do this week is figure out how to export the data from the VM that is hosting the PubDB. I've pinged Brian about this.

**Comment by arunkannawadi** [comment]
@kadrlica Do you want to keep this issue open, or open a new issue elsewhere given that much of PubDB-webpage integration work will happen after the sprint week is over.

**Comment by kadrlica** [comment]
Let's close it and open it somewhere else (maybe on `desc-pubdb`)

**Comment by arunkannawadi** [comment]
Thanks Alex! Closing this issue as the PR for this sprint is merged on to the lsstdesc.github.io repo.
