### ISSUE TITLE
[SPRINT] Start Science Planning

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/SprintWeek2021#12]
# Science Planning

Start discussions about the science planning strategy for DESC and create a handful of "artifacts" (e.g. timeline charts) to help shaping the plan

Contacts: @katrinheitmann 
Day/Time: Monday 9-10am PT, Wednesday, 8-10am PT
Main communication channel: #desc-leadership (we can discuss during the first session if there should be a dedicated slack channel for science planning)
GitHub repo: N/A
Zoom Room No. 8 (listed on [Confluence](https://confluence.slac.stanford.edu/display/LSSTDESC/DESC+2021+Sprint+Week%3A+Zoom+Sign-Ups))

## Goals and deliverable
In this sprint, we will start to think about the next phase of our Science Planning, brainstorm about the definition of good milestones, timelines. One deliverable will be an updated timeline diagram that extends to 2025.

## Resources and skills needed
Enthusiasm

## Detailed description
We will discuss the next phase in developing our science plan for DESC, how we can accommodate all the great science DESC is doing in a document but also have some clear deliverables that will prepare us for data arrival. Questions will be discussed how we can design a document that is easy to update, informative for new DESC members, useful for project management .. 

The Monday meeting will focus on developing a timeline diagram (some starting thoughts/questions are [here](https://docs.google.com/presentation/d/1-YC8gb4Xer94QVSCvsGR29eYrS0vBw9ZZcWC90Urmno/edit#slide=id.ge94127229b_0_55)) the session on Wednesday will focus on discussing a strawman for a science plan (some starting thoughts are [here](https://docs.google.com/presentation/d/1H6Oxl4Q3t3tF1vk3lUQQRAJx11eXx3WeqNz7fyuZXY4/edit#slide=id.gf2c85d2a3b_0_84).)

**Comment by rmandelb** [comment]
I self-assigned, as I'm interested in this.  However, I can only attend for part of the week (Tuesday and parts of Wednesday and Thursday).

**Comment by katrinheitmann** [comment]
Thanks all who were available to participate in the first sprint this morning! Based on our discussions, the finished the first draft of the timeline diagram going out to 2025:
![Screen Shot 2021-10-25 at 1 50 10 PM](https://user-images.githubusercontent.com/12860812/138753885-e53f35a6-9fc2-49e8-8a68-7943664cb740.png)
I will add some more text later today to have the different timelines also written down (it's also in the slides above). Have to double check that I got all the dates right..

Comments are very welcome! Thanks again!

(And from the discussion: we will add the more detailed version from v2.4 in an appendix where we can summarize some more of the outcome of the data challenges at some point as well).

**Comment by rmandelb** [comment]
Apologies that I missed it this morning - I have another commitment on Monday and Friday of this week, but will happily join the second set of discussions scheduled for Wednesday.  

I think this is a really useful update of the timeline diagram. 

Two thoughts for your consideration: 
- Might it make sense to have an arrow or something connecting the blue boxes to the appropriate Data Preview box (i.e. so it's clear that Data Preview 1 is ComCam and so on - indicate what data goes in what DP)?  
- And perhaps the bottom row should also have something explicitly showing the start of survey operations and the first 6 months of survey data that will go into DR1?  

In my experience lots of people find the connection between the timelines for observing with ComCam/LSSTCam for commissioning and SV and the Data Previews / Data Release to be confusing, and I think with small modifications it might be possible to make the figure indicate this.

**Comment by katrinheitmann** [comment]
Thanks for a useful discussion this morning. Tomorrow, I could meet at these times: 7-8am PT, 8-9am PT, 9-10am PT or 12-1pm PT. Friday I could do 7am PT-8am PT or 10-11am PT. If any of those work for others, it would be nice to have a follow up discussion.

Some conclusions from today (feel free to add) as I understood them, please correct if I did not capture them correctly:
- we want to enable the recognition of all the great science that is ongoing and also newly proposed, but at the same time we do not want to lose the focus on critical papers to be delivered with DR2; this might be enabled by a split of the SRM
- we want to understand the best "vehicles" to use for defining "deliverables", not fully clear that DESC Projects can accommodate all our needs
- we want to understand if we first write down our plan and then extract spreadsheets for tracking, or first write the spreadsheets and then ingest them into a document
- we want to make sure that we have well defined tasks on a ~one year time scale but more generally defined tasks on a longer time scale to provide flexibility (making sure that we are not losing the focus on the 2025 goals we define)

**Comment by egawiser** [comment]
I could call in for a half-hour at 8:30am PT or at 12-1 PT tomorrow, but neither Friday time works for me.  No problem if I miss the second discussion though.  In case that happens, let me re-state some proposals made on today's Zoom chat here:  
Could the beyond-one-year content be terse milestones like "validate TXPipe on commissioning data" with an expected deadline, rough-estimated FTEs to achieve them, and just a 1-2 senence explanation?  All such milestones within the next ~year would get projects declared to enable us to achieve them.   
Then (semi?-)annual updates to our plans would involve first reassessing the milestones and their timing; we should link as many as possible to DP/DR dates so that they auto-drift with any Rubin delays.  Second,  we would add projects for milestones that are newly within the "detailed planning" window.

**Comment by rmandelb** [comment]
My schedule is a train wreck, and the only one of those options that works for me is Thurs 8:30-9:30am Pacific (and I understand if you decide to proceed without me).

> Could the beyond-one-year content be terse milestones like "validate TXPipe on commissioning data" with an expected deadline, rough-estimated FTEs to achieve them, and just a 1-2 senence explanation?

+1

In the context of working towards specific early science analyses, I think it would be natural to have terse milestones of that sort along the way.  Keeping it as vague as this would avoid issues with things going stale.  And putting the details into project announcements for projects connected with near-term milestones would get the details into PubDB/confluence and other regularly-used communication channels, which I think is appropriate.

**Comment by katrinheitmann** [comment]
I would be happy to meet for another 30 minutes at 8:30 PT. I'll be on zoom.

**Comment by mishakb** [comment]
I meant to respond earlier ... by magic that 1/2 hour should work for me tomorrow and then I need to run give an exam to my students! So in principle I should be able to join in that little window.

**Comment by nsevilla** [comment]
Concerning the split high level Science Planning document, if we indeed end up doing that. I believe that the main goal of having this split is to have a straightforward, concrete, introductory document that leads to the more detailed SRM. In that sense, the current first sections 1-3 of the SRM I don't think achieve this. Some of the WG info could be ported over, and the projects should be trimmed (as Mustapha I think was saying yesterday) for this introductory document. And then some of the White Paper text could be brought as well in my opinion, updating it to our current knowledge of the science case and analysis state of the art. Of course, assuming we are goint that route!

**Comment by katrinheitmann** [comment]
I am on currently at the same zoom as yesterday: https://stanford.zoom.us/j/93461996092?pwd=RUdrYkYzdnRiVmdwSk1vcFAyZ3hKUT09

**Comment by katrinheitmann** [comment]
A few more take-away messages from this sprint (please comment/correct/add):
- A basically static document that would provide a scientific overview of DESC would be useful. At the heart of it would be Section 3 of the current SRM which has a description and priorities of the working groups. This part of the SRM has gotten positive feedback in the past. In addition, we would rewrite section 1 and 2 in a more general way. The "Introduction to the Rubin Observatory LSST DESC [here](https://docs.google.com/presentation/d/1pjMeJy2OsRo8j8inBv3Qj7-dctWdKO6uEzlSIQBrkeg/edit#slide=id.g2ade3bc380_0_0) would be a complementary document that also describes some of the DESC organizational aspects. DESC Projects could still be listed to provide also a snapshot of currently ongoing science (we did not converge on what Projects would be included). The document would continue to be a latex document since it provides a clean interface and good readability.
- We developed a new timeline diagram (presented above). It still needs some small changes (suggestions also above) but overall, we were happy with it.
- We agreed that the natural science eras for DESC are Science Readiness and Early Science (and for Early Science we adopted the same definition as Rubin, including DR1 into Early Science). In addition, we want to tie our milestones to the data preview timelines (the data previews subdivide the science eras). Therefore, if the Rubin schedule shifts, so does our milestone schedule.
-  We would develop a plan out to 2025 (up to DR2), however, we would provide details only for the upcoming year to ensure that our plans stay up-to-date. Beyond-one-year content could be terse milestones like "validate TXPipe on commissioning data" with an expected deadline, rough-estimated FTEs to achieve them, and just a 1-2 senence explanation. The work for the next year would be described in more detail. We discussed if this work could be cast into DESC Projects, but it was not fully clear to everybody that DESC Projects really function well in that way. Then there would be an annual or bi-annual update. 
- The DESC Projects on the critical path would be specifically marked to distinguish them from the general R&D Projects.
- An important step would be the definition of ~5 or so Key Science Goals (we did not agree in the end of what terminology should be used here) and the working groups would be tasks with defining them.

A last comment: the pubdb system does already have the concept of "Key Projects". However, we might be totally overloading this term if we would use those for our critical path projects (since a Key Project should lead to a Key Paper and not all of our critical path projects will be Key Papers, in fact, probably few).

**Comment by katrinheitmann** [comment]
This was a very fruitful sprint and we have now a follow-up [GitHub repo](https://github.com/LSSTDESC/SciencePlanning) to continue our planning work.
