### ISSUE TITLE
[SPRINT] N5K paper writing

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/SprintWeek2021#23]
# N5K paper writing

Write the remaining background / theory sections of the N5K paper draft and start writing results sections.

Contacts: Danielle Leonard, c-d-leonard on slack
Day/Time: Tuesday, Thursday and Friday, UK working hours
Main communication channel: desc-ccl-n5k (slack)
GitHub repo: LSSTDESC/N5K

## Goals and deliverable
Finish at least the challenge setup section. Stretch goal, skeleton text for the results section.

## Resources and skills needed
Have worked on or contributed to N5K challenge

## Detailed description
paper draft is here: https://www.overleaf.com/9619758916hvcbxjnvshqh

**Comment by schoeneberg** [comment]
I would be happy to help out with the writing, especially for the section about the FFTlog code. Let me know where I can join to participate!

**Comment by c-d-leonard** [comment]
That would be awesome @schoeneberg, thank you! I am planning on getting the new kernels done (#30 ) today and will probably switch the paper writing later in the week, but if you would like to go ahead and draft something for the section that is currently a placeholder in the draft linked above for each entry, describing the code and what approach it takes, that would be amazing. Currently there is a placeholder section in IV.B for FFTlog / matter. Let me know if you are able to access it or if you need any help!

**Comment by c-d-leonard** [comment]
Progress from today and yesterday: Nils @schoeneberg gave a lot of very useful comments on the draft and drafted a section on his entry. Today I went through and incorporated his comments, as well as finishing drafting the setup section. I think in principle we have a full draft of the background / setup sections minus other entry summaries.

**Comment by c-d-leonard** [comment]
This is in pretty good shape! We now have a full draft of all the background sections other than entry summaries (we have the one for matter), and we have a skeleton of the results section awaiting plots and discussion. I'm going to consider this sprint complete!
