### ISSUE TITLE
[SPRINT] dNdz / kernels for N5K analysis

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/SprintWeek2021#30]
# dNdz / kernels for N5K analysis

To do some of the higher level evaluation of the N5K entries, we need a couple of variations on the fiducial dNdz / kernels provided in the challenge repo. The sprint is to produce these and push them to the repo.

Contacts: Danielle Leonard
Day/Time: Tuesday, Thursday or Friday, UK morning
Main communication channel: slack: desc-ccl-n5k
GitHub repo: https://github.com/LSSTDESC/N5K

## Goals and deliverable
kernels and dNdz pushed to the repo

## Resources and skills needed
python

**Comment by damonge** [comment]
When this is done I'll make it my task to generate the corresponding benchmarks! Please ping me.

**Comment by c-d-leonard** [comment]
Progress today: made dNdz's and kernels corresponding to the following cases:
- lens and source z bins both half and a quarter the width of the fiducial case (same number of bins as fiducial case, same underlying dNdz). The half tne quarter refer to the width of the top hat selection function on the true dNdz prior to applying photo-z scatter for the lenses, and the fraction of the galaxies used to create this top-hat selection function for the sources. In both cases, the sigz is scaled down relative to fiducial to avoid the photo-z uncertainty totally smearing out the reduced bin width (sigz=0.006 for lens, 0.01 for sources).
- starting from the fiducial set up, dropping either 0, 1 or 2 redshift bins starting at higher redshifts from sources and / or 0, 2 or 4 from lenses. redshift distribution of each bin is unchanged but total dNdz is different as missing higher z bins. 8 different combinations between lens and source configuration possible other than the fiducial case. sigz fiducial in this case.

These have been pushed to repo in the new_kernels branch.

I also modified the get_tracer_dNdzs and get_tracer_kernels functions in the base class to allow an optional filename argument so we can run more easily with these new files.

I also pushed the machinery used to generate the dNdz's from the 'true' dNdz from the SRD to the repo.

I won't close this issue yet because there may be some adjustments to these new kernels later in the week if comments on specific choices come from other people working on N5K. Tagging @damonge @slosar @EiffL @t-ferreira @tilmantroester @xfangcosmo for any comments here.

**Comment by c-d-leonard** [comment]
plots of the dNdz's for the half and quarter width bin case as well as fiducial for comparion

[dNdz_sources_quarterwidth_sigz0.01.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419540/dNdz_sources_quarterwidth_sigz0.01.pdf)
[dNdz_lenses_quarterwidth_sigz0.006.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419541/dNdz_lenses_quarterwidth_sigz0.006.pdf)
[dNdz_sources_halfwidth_sigz0.01.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419543/dNdz_sources_halfwidth_sigz0.01.pdf)
[dNdz_lenses_halfwidth_sigz0.006.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419544/dNdz_lenses_halfwidth_sigz0.006.pdf)
[dNdz_sources_fiducial.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419545/dNdz_sources_fiducial.pdf)
[dNdz_lenses_fiducial.pdf](https://github.com/LSSTDESC/SprintWeek2021/files/7419546/dNdz_lenses_fiducial.pdf)

**Comment by c-d-leonard** [comment]
PR to the main repo branch has been made, I am considering this sprint closed.
