### ISSUE TITLE
[SPRINT] debug issue with N5K entry on NERSC

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/SprintWeek2021#31]
# debug issue with N5K entry on NERSC

One of the N5K entries is currently giving a different delta chi squared value on NERSC vs on laptops. Figure out why and fix it.

Contacts: Danielle Leonard / Tassia Ferreira
Day/Time: not sure yet
Main communication channel: slack: desc-ccl-n5k
GitHub repo: https://github.com/LSSTDESC/N5K

## Goals and deliverable
Get agreement in this delta chi^2 between laptops and NERSC runs

## Resources and skills needed
NERSC, python

**Comment by schoeneberg** [comment]
I would love to help out with this issue/sprint! Just send me a zoom link I can join (or something similar), and I will be able to connect! (I registered through the official link, but I didn't manage to get additional access).

**Comment by c-d-leonard** [comment]
That would be so great, @schoeneberg! Ideally we want to coordinate this with @t-ferreira as she is the one who has been seeing this discrepancy, Tassia are you available at some particular time this week to zoom with Nils and maybe me also and try to figure this out?

**Comment by c-d-leonard** [comment]
@t-ferreira and @schoeneberg knocked this one out of the park yesterday! It was an issue with an old install of CLASS not being overwritten when it appeared that it should. Issue / sprint complete and closed.
